import Navigation from "@/components/Navigation";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navigation />
        <div>{children}</div>
        <div className="flex-grow mt-96"></div>
        <Footer />
      </body>
    </html>
  );
}
